FROM nsqio/nsq

    RUN echo "\n\nACCESS: http://127.0.0.1:4171\n\n\n"; \
    echo "/usr/local/bin/nsqd  -msg-timeout=8h -max-msg-timeout=24h -mem-queue-size=40 -data-path=/data -lookupd-tcp-address=0.0.0.0:4160 -broadcast-address=0.0.0.0 -log-level=DEBUG &" > /entrypoint.sh; \
    echo "/usr/local/bin/nsqlookupd &" >> /entrypoint.sh; \
    echo /usr/local/bin/nsqadmin -nsqd-http-address=127.0.0.1:4151 >> /entrypoint.sh; \
    chmod 777 /entrypoint.sh

    ENTRYPOINT /entrypoint.sh